### PR TITLE
Fix the issue that storm could be executed thousands of times if some HTTP requests take long time to return or error out

### PR DESCRIPTION
**Pull request by blu3mania**
Current way of checking timeout may be blocked by one task not coming back for a long time. It gets worse when there are many storms in a short period, as previous unfinished requests are still executing, causing slower server response, and some of the storms could be executed thousands of times, making the situation even worse. In extreme cases, the app runs out of old space heap and crashes.

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
Storm task dispatches at 60ms or at the completion of task `t`, whichever comes first. 
The case that would cause millions of requests to queue up is _the request fails or completes immediately_, causing it to spin up even more of those instant completes/failure.
Worst of all, my `RateLimiter` will process at most 50 requests per second (threshold for 412) no matter what, eventually leads to an overflow of tasks in the Circular Linked List. 
So network is a pain 233

**Comment by blu3mania** [comment]
Right, that scenario certainly could cause tons of requests. Though, in my case, the issues was caused by some requests taking too long to return. I didn't check node.js document to find out the default timeout in HTTP request, but I suspect what happened was:

- likely one request timed out, which caused Xhr to abort the connection, which in turn caused an HttpError
- BilibiliRest would retry on HttpError.
- Meanwhile, since Promise.all() was blocked, quit flag was not set, and maybe around 2 thousands requests had been sent (assuming HTTP timeout is 2 minutes), all these requests caused most of them to timeout again, including the original one, which would cause another abortion and HttpError, which would be retired for the last time, and only after that Promise.all() would be solved and quit flag set.

So assuming HTTP timeout is 2 minutes, this could easily be more than 6 minutes in execution. In the log I saw that before it crashed (running out of 2G heap space 😮) the last storm had more than 18000 executions. It was a miracle that they didn't ban my account outright. 🤣

**Comment by blu3mania** [comment]
Actually one thing I would suggest is to allow client to specify # of tries in request. For most requests like guard, gift, we certainly want to retry couple of times. However, for failed storm request there is no need to retry.

**Comment by Billyzou0741326** [comment]
Huge mistake, I implemented a default 4s timeout for the monitor but did not do the same for the client here.

**Comment by Billyzou0741326** [comment]
With storms, my observations were—requests need to come in short intervals, need to continue for a period of time, hence the 60ms per requests and 25s deadline...

For other gifts I haven't encountered signs of failure, though. Any clue what went wrong?

**Comment by blu3mania** [comment]
I haven't analyzed responses from those storm requests so I don't have a clue. I was a bit surprised when I saw the implementation since when I manually tried to claim storm from app it didn't seem to require more than one click. I will try to debug a bit but I kind of doubt if I can find anything...

**Pull request merged**
